sudo: required

services:
  - docker

script:
  - ./abstat.sh build
  - testing/test-java-ui-module.sh
  - testing/test-java-summarization-module.sh
  - ./abstat.sh run /schema-summaries/testing/end2end-test.sh
  - ./abstat.sh destroy
  - ./abstat.sh build
  - ./abstat.sh run /schema-summaries/testing/system-tests.sh

